# Generated by Django 5.0.6 on 2024-07-18 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('location', models.TextField()),
                ('course_type', models.CharField(max_length=20)),
                ('course_duration', models.PositiveSmallIntegerField()),
                ('course_level', models.CharField(max_length=20)),
                ('course_fee', models.CharField(max_length=15)),
                ('course_trainer', models.CharField(max_length=20)),
                ('course_students', models.PositiveSmallIntegerField()),
                ('course_date', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
