# Generated by Django 5.0.6 on 2024-07-18 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_remove_student_age_remove_student_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='student',
            name='guardian',
        ),
    ]
